FROM php:fpm

RUN apt update && apt install -y

RUN apt install -y --no-install-recommends \
        git \
        openssh-server \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
        zip \
    && docker-php-ext-install \
        zip \
        intl \
        mysqli \
        pdo pdo_mysql

RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
COPY symfony/ /var/www/symfony

WORKDIR /var/www/symfony/