version: '3'

services:
  docker-nginx:
    container_name: docker-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
    - ./symfony/:/var/www/symfony/
    ports:
    - 8000:80
    networks:
      - symfony
    depends_on:
      - docker-php

  docker-php:
    container_name: docker-php
    build:
      context: .
      dockerfile: Dockerfile-php
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://user:pass@docker-mysql:3306/symfony_db?serverVersion=8
    volumes:
    - ./symfony/:/var/www/symfony/
      # TIP: Start agent in .bashrc file local ./root/
      # add your $USER/.ssh folder to local ./root
      # chmod -R 700 /root/.ssh when you're logged in as root
      # re-login use your ssh keys for git
      # git clone ssh@SymfonyRepository.git .
    - ./root/:/root/
    ports:
    - 8001:80
    networks:
      - symfony
    depends_on:
      - docker-mysql

  docker-mysql:
    container_name: docker-mysql
    image: mysql:8
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 3306:3306
    volumes:
    - ./mysql:/var/lib/mysql
    networks:
      - symfony

networks:
  symfony: